name: Run tox

on:
  pull_request:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        toxenv: [core, lint]
        include:
          - python-version: "3.10"
            toxenv: docs
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set TOXENV
        run: |
          if [[ "${{ matrix.toxenv }}" == "docs" ]]; then
            echo "TOXENV=docs" >> "$GITHUB_ENV"
          else
            python_version="${{ matrix.python-version }}"
            echo "TOXENV=py${python_version//./}-${{ matrix.toxenv }}" >> "$GITHUB_ENV"
          fi
      - run: |
          python -m pip install --upgrade pip
          python -m pip install "tox>=4.10"
      - run: |
          python -m tox run -e "$TOXENV" -r

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        toxenv: [core, lint]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set TOXENV
        shell: bash
        run: |
          python_version="${{ matrix.python-version }}"
          echo "TOXENV=py${python_version//./}-${{ matrix.toxenv }}" >> "$GITHUB_ENV"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "tox>=4.10"
      - name: Test with tox
        shell: bash
        run: |
          python -m tox run -e "$TOXENV" -r
